// Generates the offline service worker from the FINAL built output so the
// precache list always matches the hashed artifacts — never hand-maintained.
import { createHash } from "node:crypto";
import { readdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

function listFiles(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(directory, entry.name);
    return entry.isDirectory() ? listFiles(path) : [path];
  });
}

export async function generateServiceWorker({ distDir, base }) {
  const root = resolve(distDir);
  const files = listFiles(root)
    .map((path) => relative(root, path).split(sep).join("/"))
    .filter((path) => path !== "sw.js")
    .sort();
  const version = createHash("sha256").update(JSON.stringify(files)).digest("hex").slice(0, 12);
  const cacheName = `jeerah-demo-${version}`;
  const urls = files.map((path) => `${base}${path}`);

  const source = `/* Generated by scripts/generate-sw.mjs — do not edit by hand. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const BASE = ${JSON.stringify(base)};
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys
          .filter((key) => key.startsWith("jeerah-demo-") && key !== CACHE_NAME)
          .map((key) => caches.delete(key)),
      ))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(fetch(request).catch(() => caches.match(BASE + "index.html")));
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      const refresh = fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            void caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => cached);
      return cached ?? refresh;
    }),
  );
});
`;

  const swPath = join(root, "sw.js");
  writeFileSync(swPath, source);
  return swPath;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = new Map(
    process.argv.slice(2).map((argument) => {
      const [key, value] = argument.split("=");
      return [key.replace(/^--/, ""), value];
    }),
  );
  const distDir = args.get("dist") ?? "dist/client";
  const base = args.get("base") ?? "/";
  const swPath = await generateServiceWorker({ distDir, base });
  console.log(`generate-sw: wrote ${swPath}`);
}
