import type {
  Activity, AmenityBooking, Announcement, Building, CommunityEvent, DemoState, Invoice, MemberOffer,
  NeighborDeal, NeighborGift, NeighborRelationship, OrderStatus, Payment, Poll, RecurringPlan, Resident,
  RequiredServiceKey, ServiceFamily, ServiceFamilyId, ServiceOffering, ServiceOrder, ServiceProvider,
  Unit, VisitorPass,
} from "./models";

export const BUILDING_IDS = ["building-89", "nakheel-court", "jeddah-view", "wadi-homes"] as const;
export const SERVICE_FAMILY_IDS = ["care-cleaning", "home-maintenance", "building-tech-safety", "water-utilities", "automotive-mobility", "daily-needs", "home-fitout-moving", "community-membership"] as const;
export const CURRENT_RESIDENT_ID = "resident-saif";
export const CURRENT_BUILDING_ID = "building-89";

const DATE = "2026-08-03T12:00:00+03:00";
const text = (ar: string, en: string) => ({ ar, en });

const buildings: Building[] = [
  ["building-89", "مبنى ٨٩", "Building 89", "الرياض، حي الياسمين", "Riyadh, Al Yasmin", "فريق جيرة", "Jeerah Team"],
  ["nakheel-court", "مجمع النخيل", "Nakheel Court", "الرياض، النخيل", "Riyadh, Al Nakheel", "سارة العتيبي", "Sara Alotaibi"],
  ["jeddah-view", "إطلالة جدة", "Jeddah View", "جدة، الشاطئ", "Jeddah, Al Shati", "فهد الحربي", "Fahad Alharbi"],
  ["wadi-homes", "منازل الوادي", "Wadi Homes", "الدمام، الفيصلية", "Dammam, Al Faisaliyah", "ريم السالم", "Reem Alsalem"],
].map(([id, arName, enName, arAddress, enAddress, arManager, enManager]) => ({
  id, name: text(arName, enName), address: text(arAddress, enAddress), manager: text(arManager, enManager), imageIds: ["building-exterior"], amenityIds: ["lounge", "gym"],
}));

const unitIds = ["unit-89-101", "unit-89-202", "unit-89-303", "unit-nakheel-101", "unit-nakheel-202", "unit-nakheel-303", "unit-jeddah-101", "unit-jeddah-202", "unit-jeddah-303", "unit-wadi-101", "unit-wadi-202", "unit-wadi-303"];
const units: Unit[] = unitIds.map((id, index) => ({
  id, buildingId: BUILDING_IDS[Math.floor(index / 3)], label: text(`شقة ${101 + (index % 3) * 101}`, `Apartment ${101 + (index % 3) * 101}`), floor: (index % 3) + 1,
  status: index === 8 ? "maintenance" : index === 11 ? "vacant" : "occupied", residentIds: [], imageIds: ["unit-living-room"],
}));
const residents: Resident[] = [
  ["resident-saif", "unit-89-101", "سيف الشمري", "Saif Alshammari", "owner", "active"], ["resident-lina", "unit-89-202", "لينا الحربي", "Lina Alharbi", "tenant", "active"],
  ["resident-omar", "unit-89-303", "عمر العتيبي", "Omar Alotaibi", "family", "active"], ["resident-noura", "unit-nakheel-101", "نورة السالم", "Noura Alsalem", "owner", "active"],
  ["resident-yara", "unit-nakheel-202", "يارا الدوسري", "Yara Aldosari", "tenant", "active"], ["resident-hassan", "unit-jeddah-101", "حسن الغامدي", "Hassan Alghamdi", "owner", "active"],
  ["resident-maha", "unit-jeddah-202", "مها القحطاني", "Maha Alqahtani", "tenant", "invited"], ["resident-adel", "unit-wadi-101", "عادل السبيعي", "Adel Alsubaie", "owner", "inactive"],
].map(([id, unitId, ar, en, role, status]) => ({ id, unitId, name: text(ar, en), role: role as Resident["role"], status: status as Resident["status"] }));
for (const unit of units) unit.residentIds = residents.filter((resident) => resident.unitId === unit.id).map((resident) => resident.id);

const invoiceRows: Array<[string, string, string | undefined, string | undefined, string, string, number, Invoice["status"]]> = [
  ["invoice-elevator", "building-89", "unit-89-101", "resident-saif", "صيانة المصعد", "Elevator maintenance", 700, "due"], ["invoice-89-paid-1", "building-89", "unit-89-202", "resident-lina", "رسوم اتحاد الملاك", "HOA fee", 950, "paid"],
  ["invoice-89-paid-2", "building-89", "unit-89-303", "resident-omar", "خدمات المبنى", "Building services", 450, "paid"], ["invoice-89-paid-3", "building-89", undefined, undefined, "صيانة المداخل", "Entrance maintenance", 300, "paid"],
  ["invoice-nakheel-due", "nakheel-court", "unit-nakheel-101", "resident-noura", "فاتورة ماء", "Water invoice", 260, "due"], ["invoice-nakheel-overdue", "nakheel-court", "unit-nakheel-202", "resident-yara", "رسوم تأخير", "Late fee", 180, "overdue"],
  ["invoice-jeddah-upcoming", "jeddah-view", "unit-jeddah-101", "resident-hassan", "تنظيف الخزان", "Tank cleaning", 520, "upcoming"], ["invoice-jeddah-paid", "jeddah-view", "unit-jeddah-202", "resident-maha", "اشتراك الأمن", "Security subscription", 330, "paid"],
  ["invoice-wadi-due", "wadi-homes", "unit-wadi-101", "resident-adel", "صيانة دورية", "Routine maintenance", 410, "due"], ["invoice-wadi-upcoming", "wadi-homes", undefined, undefined, "تشجير الحي", "Neighborhood landscaping", 680, "upcoming"],
];
const invoices: Invoice[] = invoiceRows.map(([id, buildingId, unitId, residentId, ar, en, subtotal, status], index) => ({ id, buildingId, unitId, residentId, title: text(ar, en), category: "demo", subtotal, tax: 0, total: subtotal, dueDate: `2026-08-${String(4 + index).padStart(2, "0")}T12:00:00+03:00`, status, createdAt: DATE }));

const serviceFamilies: ServiceFamily[] = [
  ["care-cleaning", "العناية والتنظيف", "Care & cleaning", "خدمات نظافة المنزل والمبنى", "Home and building cleaning", "sparkle"], ["home-maintenance", "صيانة المنزل", "Home maintenance", "إصلاحات موثوقة عند الطلب", "Trusted repairs on demand", "wrench"],
  ["building-tech-safety", "تقنية وسلامة المبنى", "Building tech & safety", "حماية وتحكم ذكي", "Smart protection and control", "shield"], ["water-utilities", "المياه والمرافق", "Water & utilities", "إمدادات ومرافق أساسية", "Essential utilities", "drop"],
  ["automotive-mobility", "السيارات والتنقل", "Automotive & mobility", "خدمة السيارة حيث تقيم", "Car service where you live", "car"], ["daily-needs", "الاحتياجات اليومية", "Daily needs", "طلبات سريعة للمنزل", "Quick home essentials", "basket"],
  ["home-fitout-moving", "التجهيز والنقل", "Home fitout & moving", "تجهيز المنزل والانتقال", "Fit out and move home", "sofa"], ["community-membership", "المجتمع والعضوية", "Community & membership", "عروض جيرة الخاصة", "Jeerah member benefits", "users"],
].map(([id, ar, en, arDescription, enDescription, iconKey]) => ({ id: id as ServiceFamilyId, name: text(ar, en), description: text(arDescription, enDescription), iconKey }));

type ServiceSpec = readonly [RequiredServiceKey, ServiceFamilyId, string, string, ServiceOffering["scope"], ServiceOffering["fulfillment"][number], ServiceOffering["pricingModel"]];
const serviceSpecs: ServiceSpec[] = [
  ["pest-control", "care-cleaning", "مكافحة الحشرات", "Pest control", "apartment", "scheduled", "starting-at"], ["general-maintenance", "home-maintenance", "صيانة عامة", "General maintenance", "both", "on-demand", "starting-at"], ["hourly-handyman", "home-maintenance", "فني بالساعة", "Hourly handyman", "apartment", "on-demand", "per-unit"], ["gas-delivery", "water-utilities", "توصيل الغاز", "Gas delivery", "apartment", "scheduled", "fixed"], ["water-delivery", "water-utilities", "توصيل المياه", "Water delivery", "apartment", "scheduled", "fixed"],
  ["cleaning-supplies", "daily-needs", "مستلزمات التنظيف", "Cleaning supplies", "apartment", "on-demand", "fixed"], ["elevator-maintenance", "building-tech-safety", "صيانة المصاعد", "Elevator maintenance", "building", "quote", "quote-required"], ["tank-fill", "water-utilities", "تعبئة الخزان", "Tank fill", "building", "scheduled", "starting-at"], ["sewage-service", "water-utilities", "خدمة الصرف الصحي", "Sewage service", "building", "quote", "quote-required"], ["mobile-car-wash", "automotive-mobility", "غسيل سيارات متنقل", "Mobile car wash", "apartment", "scheduled", "fixed"],
  ["mobile-car-maintenance", "automotive-mobility", "صيانة سيارات متنقلة", "Mobile car maintenance", "apartment", "quote", "quote-required"], ["mobile-tire-change", "automotive-mobility", "تغيير إطارات متنقل", "Mobile tire change", "apartment", "on-demand", "starting-at"], ["grocery-delivery", "daily-needs", "توصيل البقالة", "Grocery delivery", "apartment", "on-demand", "fixed"], ["produce-delivery", "daily-needs", "توصيل الخضار", "Produce delivery", "apartment", "scheduled", "fixed"], ["bedding-laundry", "care-cleaning", "غسيل المفروشات", "Bedding laundry", "apartment", "scheduled", "starting-at"],
  ["home-cleaning", "care-cleaning", "تنظيف المنزل", "Home cleaning", "apartment", "recurring", "starting-at"], ["camera-installation", "building-tech-safety", "تركيب كاميرات", "Camera installation", "both", "quote", "quote-required"], ["neighbor-gifts", "community-membership", "هدايا الجيران", "Neighbor gifts", "apartment", "on-demand", "fixed"], ["building-washing", "care-cleaning", "غسيل المبنى", "Building washing", "building", "scheduled", "quote-required"], ["appliance-maintenance", "home-maintenance", "صيانة الأجهزة", "Appliance maintenance", "apartment", "on-demand", "starting-at"],
  ["furniture-moving", "home-fitout-moving", "نقل الأثاث", "Furniture moving", "apartment", "quote", "quote-required"], ["fire-safety", "building-tech-safety", "السلامة من الحريق", "Fire safety", "building", "quote", "quote-required"], ["stickers-signage", "home-fitout-moving", "ملصقات ولوحات", "Stickers & signage", "both", "quote", "starting-at"], ["smart-lock-installation", "building-tech-safety", "تركيب قفل ذكي", "Smart lock installation", "apartment", "scheduled", "starting-at"], ["internet-installation", "building-tech-safety", "تركيب الإنترنت", "Internet installation", "apartment", "scheduled", "fixed"],
  ["ev-charger-installation", "building-tech-safety", "تركيب شاحن سيارات", "EV charger installation", "building", "quote", "quote-required"], ["elevator-access-controls", "building-tech-safety", "تحكم دخول المصعد", "Elevator access controls", "building", "quote", "quote-required"], ["entrance-fragrance", "care-cleaning", "تعطير المداخل", "Entrance fragrance", "building", "recurring", "starting-at"], ["awning-installation", "home-fitout-moving", "تركيب المظلات", "Awning installation", "both", "quote", "quote-required"], ["interior-design", "home-fitout-moving", "تصميم داخلي", "Interior design", "apartment", "quote", "quote-required"],
  ["shutter-installation", "home-fitout-moving", "تركيب الشتر", "Shutter installation", "apartment", "quote", "starting-at"], ["naqi-water-filtration", "water-utilities", "فلترة مياه نقي", "Naqi water filtration", "apartment", "scheduled", "starting-at"], ["hvac-maintenance", "home-maintenance", "صيانة التكييف", "HVAC maintenance", "apartment", "on-demand", "starting-at"], ["electrical-maintenance", "home-maintenance", "صيانة كهرباء", "Electrical maintenance", "both", "on-demand", "starting-at"], ["plumbing-maintenance", "home-maintenance", "صيانة سباكة", "Plumbing maintenance", "both", "on-demand", "starting-at"],
];
const serviceOfferings: ServiceOffering[] = serviceSpecs.map(([key, familyId, ar, en, scope, fulfillment, pricingModel], index) => ({ id: `service-${key}`, key, familyId, providerIds: [`provider-${(index % 18) + 1}`], name: text(ar, en), scope, fulfillment: [fulfillment], pricingModel, ...(pricingModel === "quote-required" ? {} : { price: 50 + index * 10, startingPrice: 50 + index * 10 }), etaMinutes: 30 + (index % 4) * 15, slaMinutes: 60, durationMinutes: 45, warrantyDays: 30, active: true }));
const providers: ServiceProvider[] = Array.from({ length: 18 }, (_, index) => ({ id: `provider-${index + 1}`, name: text(`مزود جيرة ${index + 1}`, `Jeerah Provider ${index + 1}`), serviceIds: serviceOfferings.filter((service) => service.providerIds.includes(`provider-${index + 1}`)).map((service) => service.id), rating: 4 + (index % 10) / 10, reviewCount: 12 + index * 7, responseMinutes: 10 + index, status: "verified-demo", imageId: "provider-avatar" }));

const orderStatuses: OrderStatus[] = ["completed", "cancelled", "scheduled", "confirmed", "assigned", "en-route", "in-progress", "awaiting-resident-approval", "awaiting-quote", "quote-ready", "refunded", "completed", "scheduled", "confirmed", "assigned", "en-route", "in-progress", "completed"];
const orders: ServiceOrder[] = orderStatuses.map((status, index) => ({ id: `order-${index + 1}`, serviceId: serviceOfferings[index].id, providerId: `provider-${(index % 18) + 1}`, buildingId: index < 4 ? "building-89" : BUILDING_IDS[Math.floor(index / 5) % 4], unitId: unitIds[index % unitIds.length], residentId: residents[index % residents.length].id, fulfillment: serviceOfferings[index].fulfillment[0], status, paymentStatus: status === "refunded" ? "refunded" : "paid", amount: 100 + index * 25, scheduledAt: DATE, etaMinutes: 30, timeline: [{ id: `timeline-${index + 1}`, status, occurredAt: DATE, note: text("تحديث تجريبي", "Demo update") }], createdAt: DATE }));

const payments: Payment[] = Array.from({ length: 12 }, (_, index) => ({ id: `payment-${index + 1}`, invoiceId: invoices[index % invoices.length].id, residentId: residents[index % residents.length].id, method: (["mada", "visa", "apple-pay"] as const)[index % 3], status: (["paid", "pending", "declined", "cancelled", "timed-out", "refunded"] as const)[index % 6], amount: 150 + index * 25, occurredAt: DATE, reference: `DEMO-${String(index + 1).padStart(4, "0")}`, last4: index % 2 === 0 ? "4455" : "4242" }));
const memberOffers: MemberOffer[] = Array.from({ length: 8 }, (_, index) => ({ id: `member-offer-${index + 1}`, serviceId: serviceOfferings[index].id, title: serviceOfferings[index].name, regularPrice: 100 + index * 20, memberPrice: 80 + index * 15, active: index !== 7 }));
const recurringPlans: RecurringPlan[] = Array.from({ length: 5 }, (_, index) => ({ id: `plan-${index + 1}`, serviceId: serviceOfferings[15 + index].id, residentId: residents[index].id, cadence: (["weekly", "monthly", "quarterly", "seasonal", "monthly"] as const)[index], nextDate: "2026-08-10T09:00:00+03:00", active: index !== 4, skippedDates: index === 2 ? ["2026-08-10T09:00:00+03:00"] : [] }));
const neighborDeals: NeighborDeal[] = [0, 1, 2].map((index) => ({ id: `deal-${index + 1}`, serviceId: serviceOfferings[27 + index].id, buildingId: "building-89", participantIds: residents.slice(0, index + 1).map((resident) => resident.id), thresholds: [{ count: 3, unitPrice: 75 }, { count: 6, unitPrice: 60 }], closesAt: "2026-08-10T18:00:00+03:00" }));
const neighborRelationships: NeighborRelationship[] = [["neighbor-1", "أم نورة", "Umm Noura", "neighbor"], ["neighbor-2", "سالم", "Salem", "friend"], ["neighbor-3", "خالد", "Khalid", "family"]].map(([id, ar, en, relation]) => ({ id, displayName: text(ar, en), relation: relation as NeighborRelationship["relation"] }));
const gifts: NeighborGift[] = [["gift-1", "service-neighbor-gifts", "resident-saif", "neighbor-1", "هدية ترحيب", "sent"], ["gift-2", "service-neighbor-gifts", "resident-lina", "neighbor-2", "شكراً لجيرتك", "redeemed"]].map(([id, serviceId, senderId, recipientRelationshipId, message, status]) => ({ id, serviceId, senderId, recipientRelationshipId, message, status: status as NeighborGift["status"], createdAt: DATE }));
const announcements: Announcement[] = [
  ["announcement-1", "building-89", "تنبيه المصعد", "Elevator notice", "سيتم فحص المصعد مساءً", "The elevator will be inspected this evening", "urgent"], ["announcement-2", "building-89", "تنظيف المداخل", "Entrance cleaning", "تنظيف مجدول غداً", "Cleaning is scheduled tomorrow", "normal"],
  ["announcement-3", "nakheel-court", "تحديث البوابة", "Gate update", "تحديث نظام البوابة", "Gate system update", "important"], ["announcement-4", "jeddah-view", "فعالية الجيران", "Neighbor event", "نلتقي في الصالة", "Meet in the lounge", "normal"],
  ["announcement-5", "wadi-homes", "تنبيه المياه", "Water notice", "اختبار ضغط المياه", "Water pressure test", "important"], ["announcement-6", "nakheel-court", "صيانة دورية", "Routine maintenance", "صيانة خفيفة", "Minor maintenance", "normal"],
].map(([id, buildingId, arTitle, enTitle, arBody, enBody, priority]) => ({ id, buildingId, title: text(arTitle, enTitle), body: text(arBody, enBody), priority: priority as Announcement["priority"], publishedAt: DATE }));
const polls: Poll[] = ["building-89", "nakheel-court"].map((buildingId, index) => ({ id: `poll-${index + 1}`, buildingId, question: text("ما أفضل وقت للتنظيف؟", "What is the best cleaning time?"), options: [{ id: `poll-${index + 1}-morning`, label: text("الصباح", "Morning"), voterIds: ["resident-saif"] }, { id: `poll-${index + 1}-evening`, label: text("المساء", "Evening"), voterIds: [] }], closesAt: "2026-08-08T20:00:00+03:00" }));
const events: CommunityEvent[] = ["building-89", "jeddah-view"].map((buildingId, index) => ({ id: `event-${index + 1}`, buildingId, title: text("لقاء الجيران", "Neighbor meetup"), startsAt: "2026-08-12T19:00:00+03:00", attendeeIds: residents.slice(0, index + 2).map((resident) => resident.id), capacity: 30 }));
const visitorPasses: VisitorPass[] = Array.from({ length: 5 }, (_, index) => ({ id: `pass-${index + 1}`, buildingId: BUILDING_IDS[index % 4], unitId: unitIds[index], residentId: residents[index].id, guestName: `Guest ${index + 1}`, expiresAt: "2026-08-04T12:00:00+03:00", status: (["active", "expired", "revoked", "active", "active"] as const)[index] }));
const amenityBookings: AmenityBooking[] = Array.from({ length: 6 }, (_, index) => ({ id: `booking-${index + 1}`, buildingId: BUILDING_IDS[index % 4], residentId: residents[index].id, amenityId: index % 2 ? "gym" : "lounge", startsAt: "2026-08-05T18:00:00+03:00", status: (["upcoming", "completed", "cancelled", "upcoming", "completed", "upcoming"] as const)[index] }));
const activities: Activity[] = Array.from({ length: 12 }, (_, index) => ({ id: `activity-${index + 1}`, buildingId: BUILDING_IDS[index % 4], kind: "demo", title: text("تحديث المجتمع", "Community update"), occurredAt: DATE }));

export function createSeedState(_now: Date = new Date(DATE)): DemoState {
  return structuredClone({ schemaVersion: 1, locale: "ar", scenario: "normal", currentResidentId: CURRENT_RESIDENT_ID, currentBuildingId: CURRENT_BUILDING_ID, buildings, units, residents, invoices, payments, serviceFamilies, serviceOfferings, providers, orders, memberOffers, recurringPlans, neighborDeals, neighborRelationships, announcements, polls, events, visitorPasses, amenityBookings, gifts, activities, auditLog: [] } satisfies DemoState);
}
